version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - mongonet
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "test"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "test"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "test"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "adminpassword"
    links:
      - mongodb
    networks:
      - mongonet
networks:
  mongonet:
    driver: bridge
    